### ISSUE TITLE
download error in ubuntu

### ISSUE THREAD

**Issue by vikashinchennai** [Stormiix/pluralsight_scraper#5]
I am getting below error

root@account:~/upload/pluralsight_scraper#  python pluralsight.py
Traceback (most recent call last):
  File "pluralsight.py", line 8, in <module>
    import scraper as ps
  File "/root/upload/pluralsight_scraper/scraper.py", line 50
    print("Loading .. " + Website, end =' ')
                                       ^
SyntaxError: invalid syntax
root@account:~/upload/pluralsight_scraper#

**Comment by Stormix** [comment]
Make sure you're using python 3.x

Try running it using : python3 pluralsight.py
